### PR TITLE
drivers/audio/stream.h: add missing include

### PR DESCRIPTION
**Pull request by minexew**

### CODE REVIEW

**Review by pent0 — APPROVED** [review]
Sorry we have to resolve the CI for Android first, cause if merge to master now the Android binary will disappear. It's valid though

**Comment by yfaizin1** [comment]
ask how  to dumper file roms in phone symbian os exampel : s60v1(n-gage), s60v2(?), s60v3(5320, e5), s60v5(5530 & 5800), annabelle(c7), belle fp2? i'm trail in nokia 700 belle fp2 zonk. can you help me to, to give this tutorial

**Comment by pent0** [comment]
I dont know the error code nor ypu give me any clues to indicate the issue. Please use Discord for support forum. This Github is only for development. If neccessary open separate github issue.

**Comment by pent0** [comment]
Sorry for long wait seems the CI just fail here for some reasons

**Pull request merged**
